Repository zcash/wallet, pull requests merged in 2025-09, with the labels that each got.

#216 rpc: Add transparent information to `z_viewtransaction`
  book/src/zcashd/json_rpc.md
  zallet/src/components/json_rpc/methods.rs
  zallet/src/components/json_rpc/methods/view_transaction.rs
Labels: A-rpc-interface

#239 rpc: Add `account_uuid` fields to spends and outputs in `z_viewtransaction`
  book/src/zcashd/json_rpc.md
  zallet/src/components/json_rpc/methods.rs
  zallet/src/components/json_rpc/methods/view_transaction.rs
Labels: A-rpc-interface

#247 rpc: Use correct index for `z_viewtransaction` input lookups
  zallet/src/components/json_rpc/methods/view_transaction.rs
Labels: A-rpc-interface, C-bug

#280 Fill out documentation and adjust some commands
  README.md
  book/src/README.md
  book/src/SUMMARY.md
  book/src/cli/README.md
  book/src/cli/example-config.md
  book/src/cli/generate-mnemonic.md
  book/src/cli/import-mnemonic.md
  book/src/cli/init-wallet-encryption.md
  book/src/cli/migrate-zcash-conf.md
  book/src/cli/migrate-zcashd-wallet.md
  book/src/cli/start.md
  book/src/guide/installation/README.md
  zallet/i18n/en-US/zallet.ftl
  zallet/src/cli.rs
  zallet/src/commands/generate_mnemonic.rs
  zallet/src/commands/migrate_zcashd_wallet.rs
Labels: A-documentation

#243 cli: Add `zallet export-mnemonic`
  book/src/SUMMARY.md
  book/src/cli/README.md
  book/src/cli/export-mnemonic.md
  zallet/Cargo.toml
  zallet/src/cli.rs
  zallet/src/commands.rs
  zallet/src/commands/export_mnemonic.rs
  zallet/src/components/keystore.rs
Labels: C-feature-request

#245 rpc (z_listtransactions): Add a rudimentary transaction listing utility.
  zallet/src/cli.rs
  zallet/src/components/json_rpc/methods.rs
  zallet/src/components/json_rpc/methods/list_transactions.rs
Labels: C-feature-request

#285 CI: Upload apt repo metadata to correct bucket location
  .github/workflows/deb-release.yml
Labels: A-packaging, A-build
